#ifndef WEB_INTERFACE_H
#define WEB_INTERFACE_H

const char html_content[] =
"<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>硬件控制面板</title>"
"<style>"
"body{font-family:sans-serif;padding:10px;max-width:900px;margin:auto;background-color:#f0f0f0;}"
".control-group{background-color:#fff;padding:15px;margin-bottom:15px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1);}"
"h3{margin-top:0;border-bottom:1px solid #eee;padding-bottom:5px;color:#333;}"
"label{display:block;margin:10px 0 6px;font-weight:bold;color:#555;}"
"input[type=\"range\"]{width:75%;vertical-align:middle;}"
".value-span{display:inline-block;min-width:42px;text-align:right;font-weight:bold;color:#007bff;margin-left:10px;}"
".button-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px;}"
"button{padding:10px;font-size:1em;cursor:pointer;border:none;border-radius:5px;background-color:#007bff;color:white;transition:background-color 0.2s;}"
"button:hover{background-color:#0056b3;}"
"button.stop{background-color:#dc3545;} .button.stop:hover{background-color:#c82333;}"
"button.start{background-color:#28a745;} .button.start:hover{background-color:#218838;}"
"select,input[type=\"text\"],input[type=\"password\"],input[type=\"number\"]{width:calc(100% - 22px);padding:10px;margin-bottom:10px;border:1px solid #ccc;border-radius:4px;}"
".wifi-btn{background-color:#ffc107;color:#333;} .wifi-btn:hover{background-color:#e0a800;}"
".rgb-controls{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:15px;}"
".rgb-control{background-color:#f9f9f9;padding:10px;border-radius:5px;}"
".screen-btn{background-color:#6f42c1;} .screen-btn:hover{background-color:#5a32a3;}"
".two-col{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:center;}"

/* 摄像头 + 摇杆 */
"#camera_wrap{display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap;}"
"#camera_area{width:220px;height:165px;background:#000;border-radius:8px;overflow:hidden;display:flex;align-items:center;justify-content:center;color:#fff;}"
"#cam_feed{width:100%;height:100%;object-fit:cover;display:none;}"
"#joy_area{position:relative;width:200px;height:200px;border-radius:50%;background:#f4f5f7;border:1px solid #dcdfe6;box-shadow:inset 0 2px 6px rgba(0,0,0,.06);}"
"#joy_knob{position:absolute;width:56px;height:56px;border-radius:50%;background:#2b90ff;opacity:.9;left:72px;top:72px;box-shadow:0 4px 10px rgba(0,0,0,.15);} "
"#joy_axes{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;color:#333;margin-top:8px;}"
"</style>"
"</head>"
"<body>"
"<h1>硬件控制面板</h1>"

/* === 舵机校准（原样） === */
"<div class=\"control-group\">"
"<h3>舵机校准</h3>"
"<div style=\"display:flex; flex-wrap:wrap; gap:15px;\">"
"<div style=\"flex:1; min-width:250px;\">"
"<h4>左舵机</h4>"
"<div style=\"display:flex; align-items:center; margin-bottom:10px;\">"
"<label style=\"width:100px;\">偏移值:</label>"
"<input type=\"number\" id=\"servo1_offset\" value=\"0\" style=\"width:80px;\">"
"</div>"
"<div class=\"button-grid\">"
"<button type=\"button\" onclick=\"testServo('servo1', 0)\">0°</button>"
"<button type=\"button\" onclick=\"testServo('servo1', 45)\">45°</button>"
"<button type=\"button\" onclick=\"testServo('servo1', 90)\">90°</button>"
"<button type=\"button\" onclick=\"testServo('servo1', 135)\">135°</button>"
"<button type=\"button\" onclick=\"testServo('servo1', 180)\">180°</button>"
"</div></div>"

"<div style=\"flex:1; min-width:250px;\">"
"<h4>右舵机</h4>"
"<div style=\"display:flex; align-items:center; margin-bottom:10px;\">"
"<label style=\"width:100px;\">偏移值:</label>"
"<input type=\"number\" id=\"servo2_offset\" value=\"0\" style=\"width:80px;\">"
"</div>"
"<div class=\"button-grid\">"
"<button type=\"button\" onclick=\"testServo('servo2', 0)\">0°</button>"
"<button type=\"button\" onclick=\"testServo('servo2', 45)\">45°</button>"
"<button type=\"button\" onclick=\"testServo('servo2', 90)\">90°</button>"
"<button type=\"button\" onclick=\"testServo('servo2', 135)\">135°</button>"
"<button type=\"button\" onclick=\"testServo('servo2', 180)\">180°</button>"
"</div></div>"
"</div>"
"<button type=\"button\" onclick=\"saveServoOffsets()\" style=\"margin-top:10px;\">保存偏移值</button>"
"</div>"

/* === 摄像头 + 圆形摇杆（合并） === */
"<div class=\"control-group\">"
"<h3>摄像头 & 电机（圆形摇杆）</h3>"
"<div id=\"camera_wrap\">"
"  <div>"
"    <div id=\"camera_area\">"
"      <img id=\"cam_feed\" alt=\"摄像头预览\">"
"      <span id=\"cam_placeholder\">预览未开启</span>"
"    </div>"
"    <button type=\"button\" id=\"camera_toggle\" class=\"start\" style=\"margin-top:10px;\">开启摄像头</button>"
"  </div>"
"  <div>"
"    <div id=\"joy_area\"><div id=\"joy_knob\"></div></div>"
"    <div id=\"joy_axes\">x=0.00, y=0.00</div>"
"    <div style=\"margin-bottom:6px;\">摇杆持续时间(ms)：<input type=\"number\" id=\"joy_duration\" value=\"1000\" style=\"width:120px\"></div>"
"  </div>"
"</div>"
"</div>"

/* === 麦克风增益 === */
"<div class=\"control-group\">"
"<h3>麦克风增益</h3>"
"<div class=\"two-col\">"
"  <div><label>模拟麦克风增益 (dB)：-12 ~ 36</label>"
"  <input type=\"range\" id=\"mic_ag\" min=\"-12\" max=\"36\" value=\"0\" oninput=\"document.getElementById('mic_ag_val').textContent=this.value\"></div>"
"  <div><span class=\"value-span\" id=\"mic_ag_val\">0</span></div>"
"</div>"
"<div class=\"two-col\">"
"  <div><label>数字麦克风增益 (dB)：-83 ~ 42</label>"
"  <input type=\"range\" id=\"mic_dg\" min=\"-83\" max=\"42\" value=\"0\" oninput=\"document.getElementById('mic_dg_val').textContent=this.value\"></div>"
"  <div><span class=\"value-span\" id=\"mic_dg_val\">0</span></div>"
"</div>"
"<button type=\"button\" id=\"mic_set\" style=\"margin-top:10px;\">设置增益</button>"
"</div>"

/* === RGB 灯 & 屏幕 & WiFi（原样省略不变动，保持你之前的块） === */
"<div class=\"control-group\">"
"<h3>RGB 灯控制</h3>"
"<div class=\"button-grid\">"
"<button type=\"button\" data-led=\"rainbow\">彩虹</button>"
"<button type=\"button\" data-led=\"breathing\">呼吸</button>"
"<button type=\"button\" data-led=\"blink\">闪烁</button>"
"<button type=\"button\" data-led=\"off\" class=\"stop\">关闭</button>"
"</div>"
"<label for=\"led_period\">周期(ms): <input type=\"number\" id=\"led_period\" value=\"2000\"></label>"
"<div class=\"rgb-controls\">"
"<div class=\"rgb-control\">"
"<div>左灯颜色:</div>"
"<div class=\"color-picker\">"
"<div class=\"color-box\" style=\"background-color:#ff0000\" data-color=\"0xFF0000\"></div>"
"<div class=\"color-box\" style=\"background-color:#00ff00\" data-color=\"0x00FF00\"></div>"
"<div class=\"color-box\" style=\"background-color:#0000ff\" data-color=\"0x0000FF\"></div>"
"<div class=\"color-box\" style=\"background-color:#ffff00\" data-color=\"0xFFFF00\"></div>"
"<div class=\"color-box\" style=\"background-color:#ff00ff\" data-color=\"0xFF00FF\"></div>"
"<div class=\"color-box\" style=\"background-color:#00ffff\" data-color=\"0x00FFFF\"></div>"
"</div>"
"<input type=\"text\" id=\"left_color\" value=\"0xFF0000\" readonly>"
"</div>"
"<div class=\"rgb-control\">"
"<div>右灯颜色:</div>"
"<div class=\"color-picker\">"
"<div class=\"color-box\" style=\"background-color:#ff0000\" data-color=\"0xFF0000\"></div>"
"<div class=\"color-box\" style=\"background-color:#00ff00\" data-color=\"0x00FF00\"></div>"
"<div class=\"color-box\" style=\"background-color:#0000ff\" data-color=\"0x0000FF\"></div>"
"<div class=\"color-box\" style=\"background-color:#ffff00\" data-color=\"0xFFFF00\"></div>"
"<div class=\"color-box\" style=\"background-color:#ff00ff\" data-color=\"0xFF00FF\"></div>"
"<div class=\"color-box\" style=\"background-color:#00ffff\" data-color=\"0x00FFFF\"></div>"
"</div>"
"<input type=\"text\" id=\"right_color\" value=\"0x00FF00\" readonly>"
"</div>"
"</div>"
"<button type=\"button\" id=\"set_rgb\" style=\"margin-top:15px;\">设置RGB颜色</button>"
"</div>"

"<div class=\"control-group\">"
"<h3>屏幕显示控制</h3>"
"<label for=\"screen_type\">选择屏幕模式:</label>"
"<select id=\"screen_type\">"
"<option value=\"0\">-- 请选择 --</option>"
"<option value=\"1\">数字时钟</option>"
"<option value=\"2\">表情动图</option>"
"<option value=\"3\">音乐频谱</option>"
"<option value=\"4\">眼睛效果</option>"
"<option value=\"5\">摄像头</option>"
"<option value=\"6\">招财猫</option>"
"</select>"
"<button type=\"button\" id=\"set_screen\" class=\"screen-btn\">设置屏幕模式</button>"
"</div>"

/* === 平台链路管理（读/写都回显） === */
"<div class=\"control-group\">"
"<h3>平台链路管理</h3>"
"<label>设备ID</label>"
"<input type=\"text\" id=\"device_id\" placeholder=\"点击读取后显示\" readonly>"
"<label>Product</label>"
"<input type=\"text\" id=\"link_product\" placeholder=\"输入 Product\">"
"<label>Secret</label>"
"<input type=\"password\" id=\"link_secret\" placeholder=\"输入 Secret\">"
"<label>预设链路</label>"
"<select id=\"link_preset\">"
"<option value=\"custom\">自定义</option>"
"<option value=\"default\">默认</option>"
"<option value=\"new\">最新</option>"
"</select>"
"<div class=\"button-grid\" style=\"grid-template-columns:repeat(2,1fr)\">"
"<button type=\"button\" id=\"link_read\">读取链路信息</button>"
"<button type=\"button\" id=\"link_save\" class=\"start\">保存/应用</button>"
"</div>"
"</div>"

/* === WiFi（原样） === */
"<div class=\"control-group\">"
"<h3>WiFi 配置</h3>"
"<label for=\"ssid\">WiFi 名称 (SSID):</label>"
"<input type=\"text\" id=\"ssid\" placeholder=\"输入 WiFi 名称\">"
"<label for=\"pass\">WiFi 密码:</label>"
"<input type=\"password\" id=\"pass\" placeholder=\"输入 WiFi 密码\">"
"<button type=\"button\" id=\"wifi_save\" class=\"wifi-btn\">保存 WiFi 配置</button>"
"</div>"

"<script>"
"function testServo(servoId, angle){ sendCommand(servoId,{angle}); }"
"function saveServoOffsets(){"
"  const s1=parseInt(document.getElementById('servo1_offset').value)||0;"
"  const s2=parseInt(document.getElementById('servo2_offset').value)||0;"
"  sendCommand('servo_offset',{servo1:s1,servo2:s2});"
"}"

/* 颜色拾取与 RGB */
"document.querySelectorAll('.color-box').forEach(b=>{b.addEventListener('click',function(){"
" const color=this.getAttribute('data-color');"
" const target=this.closest('.rgb-control').querySelector('input[type=\"text\"]').id;"
" document.getElementById(target).value=color;"
"})});"
"document.getElementById('set_rgb').addEventListener('click',()=>{"
" const L=parseInt(document.getElementById('left_color').value);"
" const R=parseInt(document.getElementById('right_color').value);"
" sendCommand('led',{rgb:{left:L,right:R}});"
"});"
"document.querySelectorAll('button[data-led]').forEach(btn=>btn.addEventListener('click',()=>{"
" const mode=btn.getAttribute('data-led');"
" const period=parseInt(document.getElementById('led_period').value);"
" if(mode==='off') sendCommand('led',{off:true});"
" else if(mode==='rainbow') sendCommand('led',{rainbow:{period,symmetric:true}});"
" else{"
"  const L=parseInt(document.getElementById('left_color').value);"
"  const R=parseInt(document.getElementById('right_color').value);"
"  const c=Math.round((L+R)/2);"
"  if(mode==='breathing') sendCommand('led',{breathing:{color:c,period,symmetric:true}});"
"  if(mode==='blink')     sendCommand('led',{blink:{color:c,period,symmetric:true}});"
" }"
"}));"

/* 麦克风增益 */
"document.getElementById('mic_set').addEventListener('click',()=>{"
" const ag=parseInt(document.getElementById('mic_ag').value);"
" const dg=parseInt(document.getElementById('mic_dg').value);"
" sendCommand('mic',{analog_gain:ag,digital_gain:dg});"
"});"

/* 摄像头开关 + 预览 */
"let cameraOn=false;"
"function startStream(){const img=document.getElementById('cam_feed');const ph=document.getElementById('cam_placeholder');ph.style.display='none';img.src='/stream';img.style.display='block';}"
"function stopStream(){const img=document.getElementById('cam_feed');const ph=document.getElementById('cam_placeholder');img.style.display='none';img.src='';ph.style.display='block';}"
"document.getElementById('camera_toggle').addEventListener('click',function(){"
" if(!cameraOn){sendCommand('camera',{enable:true});startStream();this.textContent='关闭摄像头';this.classList.remove('start');this.classList.add('stop');}"
" else{sendCommand('camera',{disable:true});stopStream();this.textContent='开启摄像头';this.classList.add('start');this.classList.remove('stop');}"
" cameraOn=!cameraOn;"
"});"

/* 圆形摇杆（-1~1），松手自动急停；拖动节流发送 motion */
"(function(){"
" const area=document.getElementById('joy_area');"
" const knob=document.getElementById('joy_knob');"
" const axes=document.getElementById('joy_axes');"
" const durEl=document.getElementById('joy_duration');"
" const center={x:area.clientWidth/2,y:area.clientHeight/2};"
" const maxR=area.clientWidth/2-4; const knobR=knob.clientWidth/2;"
" let dragging=false, lastSend=0;"
" function setKnob(x,y){ knob.style.left=(x-knobR)+'px'; knob.style.top=(y-knobR)+'px'; }"
" function update(e){"
"  const rect=area.getBoundingClientRect();"
"  const px=(e.touches?e.touches[0].clientX:e.clientX)-rect.left;"
"  const py=(e.touches?e.touches[0].clientY:e.clientY)-rect.top;"
"  let dx=px-center.x, dy=py-center.y;"
"  const r=Math.hypot(dx,dy);"
"  if(r>maxR){ dx=dx*maxR/r; dy=dy*maxR/r; }"
"  setKnob(center.x+dx, center.y+dy);"
"  const x=(dx/maxR).toFixed(2);"
"  const y=(-dy/maxR).toFixed(2); /* 屏幕向下为正，这里取负号让上为 +y */"
"  axes.textContent=`x=${x}, y=${y}`;"
"  const now=performance.now();"
"  if(now-lastSend>90){"
"    const duration=parseInt(durEl.value)||0;"
"    sendCommand('motor',{motion:{x:parseFloat(x),y:parseFloat(y),duration:duration}});"
"    lastSend=now;"
"  }"
" }"
" function reset(){ setKnob(center.x,center.y); axes.textContent='x=0.00, y=0.00'; sendCommand('motor',{stop:true}); }"
" area.addEventListener('mousedown',e=>{dragging=true;update(e);});"
" window.addEventListener('mousemove',e=>{if(dragging) update(e);});"
" window.addEventListener('mouseup',()=>{if(dragging){dragging=false;reset();}});"
" area.addEventListener('touchstart',e=>{dragging=true;update(e);},{passive:false});"
" area.addEventListener('touchmove',e=>{if(dragging){update(e);}}, {passive:false});"
" area.addEventListener('touchend',()=>{if(dragging){dragging=false;reset();}});"
" setKnob(center.x,center.y);"
"})();"

/* 屏幕 */
"document.getElementById('set_screen').addEventListener('click',()=>{"
" const t=parseInt(document.getElementById('screen_type').value);"
" if(t>0) sendCommand('screen',{type:t}); else alert('请选择有效的屏幕模式');"
"});"

/* 平台链路管理（读/写，展示回显） */
"function fillLinkFromResp(data){"
" if(!data) return;"
" if(data.device_id) document.getElementById('device_id').value=data.device_id;"
" if(data.link){"
"   if(data.link.product!==undefined) document.getElementById('link_product').value=data.link.product;"
"   if(data.link.secret!==undefined)  document.getElementById('link_secret').value=data.link.secret;"
"   if(data.link.preset!==undefined)  document.getElementById('link_preset').value=data.link.preset;"
" }"
"}"
"document.getElementById('link_read').addEventListener('click',async()=>{"
" const r=await sendCommand('link',{query:true}); fillLinkFromResp(r);"
"});"
"document.getElementById('link_save').addEventListener('click',async()=>{"
" const product=document.getElementById('link_product').value.trim();"
" const secret =document.getElementById('link_secret').value.trim();"
" const preset =document.getElementById('link_preset').value;"
" const payload={}; if(product) payload.product=product; if(secret) payload.secret=secret; if(preset) payload.preset=preset;"
" const r=await sendCommand('link',payload); fillLinkFromResp(r);"
"});"

/* WiFi */
"document.getElementById('wifi_save').addEventListener('click',()=>{"
" const ssid=document.getElementById('ssid').value; const pass=document.getElementById('pass').value;"
" if(ssid) sendCommand('wifi',{ssid,pass}); else alert('请输入WiFi名称(SSID)');"
"});"

/* 统一发送，返回 JSON */
"function sendCommand(device,data){"
" const payload=JSON.stringify({[device]:data});"
" return fetch('/',{method:'POST',headers:{'Content-Type':'application/json'},body:payload})"
"   .then(r=>r.json()).catch(e=>{console.error(e);return null;});"
"}"
"</script>"
"</body>"
"</html>";

#endif
