#ifndef __APP_OBJ_REC_H__
#define __APP_OBJ_REC_H__

#include "stdint.h"

enum {
	APP_OBJ_REC_MSG_ID_NONE = 0,
	APP_OBJ_REC_MSG_ID_UI_START,
	APP_OBJ_REC_MSG_ID_UI_ENTER = APP_OBJ_REC_MSG_ID_UI_START,
	APP_OBJ_REC_MSG_ID_UI_EXIT,
	APP_OBJ_REC_MSG_ID_UI_TAKE_PICTURE,
	APP_OBJ_REC_MSG_ID_UI_BACK_TO_PREVIEW,
	APP_OBJ_REC_MSG_ID_UI_OBJ_RECOGNITION,
	APP_OBJ_REC_MSG_ID_CAMERA_START,
	APP_OBJ_REC_MSG_ID_CAMERA_NEW_PICTURE = APP_OBJ_REC_MSG_ID_CAMERA_START,
	APP_OBJ_REC_MSG_ID_MAX,
};

enum {
	APP_OBJ_REC_EVT_NONE = 0,
	APP_OBJ_REC_EVT_UI_START,
	APP_OBJ_REC_EVT_UI_PICTURE_DISPLAY = APP_OBJ_REC_EVT_UI_START,
	APP_OBJ_REC_EVT_UI_ERR_OCCURRED,
	APP_OBJ_REC_EVT_UI_ERR_PROCESSING,
	APP_OBJ_REC_EVT_UI_RESULT_COMPLETE,
	APP_OBJ_REC_EVT_UI_RESULT_START,
	APP_OBJ_REC_EVT_UI_RESULT_CONTINUE,
	APP_OBJ_REC_EVT_UI_RESULT_END,
	APP_OBJ_REC_EVT_TTS_RESULT,
	APP_OBJ_REC_EVT_TEXT_RESULT,
	APP_OBJ_REC_EVT_MAX,
};

struct app_obj_rec_msg {
	uint32_t id;
	void *data;
	uint32_t len;
};

void app_obj_rec_msg_send(uint32_t id, void *data, uint32_t len);
void app_obj_rec_ui_evt_notify(uint32_t evt, void *data, uint32_t size);

#endif
